export const LOGIN_USER = "LOGIN_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERBYID = "FETCH_USERBYID";
export const SAVE_USER = "SAVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const GET_APPOINTMENTBYID = "GET_APPOINTMENTBYID";
export const SAVE_APPOINTMENT = "SAVE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

export const GET_TIMETABLE = "GET_TIMETABLE";
export const GET_TIMETABLEBYID = "GET_TIMETABLEBYID";
export const SAVE_TIMETABLE = "SAVE_TIMETABLE";
export const DELETE_TIMETABLE = "DELETE_TIMETABLE";
