### define service setting 
@DataEndPoint = http://localhost:3005/api

### ------------------------------------------------------------------------------------
### Generate Token
# @name auth
post {{DataEndPoint}}/token
Content-Type: application/x-www-form-urlencoded

username=admin&password=123&grant_type=password


### getAppointment
POST {{DataEndPoint}}/appointment/getAppointmentList
Content-Type: application/json
Authorization: Bearer {{auth.response.body.access_token}}


### getAppointmentByID
POST {{DataEndPoint}}/appointment/getAppointmentByID?appoint_id_f=1
Content-Type: application/json
Authorization: Bearer {{auth.response.body.access_token}}


### saveAppointment
POST {{DataEndPoint}}/appointment/saveAppointment
Content-Type: application/json
Authorization: Bearer {{auth.response.body.access_token}}

{
  "appoint_id_f": 0,
  "user_id_f": 1,
  "date_f": "2021-02-1T00:00:00",
  "is_appoint_f": true
}

### deleteAppointment
POST {{DataEndPoint}}/appointment/deleteAppointment?appoint_id_f=1021
Content-Type: application/json
Authorization: Bearer {{auth.response.body.access_token}}
